name: Java CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Cache gradle cache
      uses: actions/cache@v1.1.0
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-cache${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-cache
    - name: Cache gradle wrapper
      uses: actions/cache@v1.1.0
      with:
        path: |
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-wrapper
    - name: Setup Gradle
      run: ./gradlew
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        GITHUB_PACKAGE_READ_TOKEN: ${{ secrets.GITHUB_PACKAGE_READ_TOKEN }}
    - name: Build with Gradle
      run: ./gradlew build
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        GITHUB_PACKAGE_READ_TOKEN: ${{ secrets.GITHUB_PACKAGE_READ_TOKEN }}
